<!DOCTYPE html>
<title>Database Storage - Success callback not called on error</title>
<pre id="result">FAIL - Script did not execute</pre>

<script>
//Database openDatabase(in DOMString name, in DOMString version, in DOMString displayName, in unsigned long estimatedSize);
var result = document.getElementById("result");
result.innerHTML = "";

function record(pass, msg) {
	result.innerHTML += (pass ? "PASS" : "FAIL") + (msg ? " - " + msg : "") + "\n";
	try{top.opener.rr(pass);}catch(e){}
}

function error() {
	e = arguments.length == 1 ? arguments[0] : arguments[1];
	record(false, "Error " + e.code + ": " + e.message);
}

function createTable(transaction) {
	//void executeSql(sqlStatement, [arguments], callback, errorCallback);
	transaction.executeSql("DROP TABLE IF EXISTS t;", [], null, error);
	transaction.executeSql("CREATE TABLE t(id INTEGER, label TEXT);", [], null, error);
	throw "die!";
}

var passed = true; // this is needed since if this test fails successCallback might run before errorCallback

function errorCallback() {
	if (passed) {
		record(true);
	}
}

function successCallback() {
	passed = false;
	record(false, "Success callback ran");
}

try {
	opera.deleteDatabase("test106");
	var db = window.openDatabase("test106", "", "Test DB", "100000");
	db.transaction(createTable, errorCallback, successCallback);
} catch (e) {
	record(false, "Couldn't create database or complete transaction: " + e);
}
</script>
