<!--
for (;) // should cause onerror to be invoked, but onerror is null, so
        // the error is "not handled". should fire an ErrorEvent on the
        // worker.
  break;
postMessage(1); // shouldn't do anything since the script doesn't compile
/*
-->
<!doctype html>
<title>AbstractWorker.onerror</title>
<script src="/resources/jsframework.js"></script>
<script>
test(function() {
  var worker = new Worker('#');
  var gotError = false;
  worker.onerror = function(a, b, c) {
    test(function test_interface(){
      assertEquals('' + a, '[object ErrorEvent]');
    }, 'none');
    test(function test_message(){
      assertDefined(a.message, 'ErrorEvent.message');
    }, 'none');
    test(function test_filename(){
      assertEquals(a.filename, document.URL + '#', 'ErrorEvent.filename');
    }, 'none');
    test(function test_lineno(){
      assertDefined(a.lineno, 'ErrorEvent.lineno');
    }, 'none');
    test(function test_initErrorEvent(){
      assertDefined(a.initErrorEvent, 'ErrorEvent.initErrorEvent');
    }, 'none');
    test(function test_second_arg(){
      assertUndefined(b, 'unexpected second argument to onerror');
    }, 'none');
    test(function test_third_arg(){
      assertUndefined(c, 'unexpected third argument to onerror');
    }, 'none');
    gotError = true;
  }
  worker.onmessage = function(e) {
    test(function() {
      assertUnreached('onmessage was invoked but worker script shouldn\'t have compiled');
    }, 'none');
  }
  test(function() { assertTrue(gotError) }, 1000);
});
</script>
<!--
*/
//-->


